name:                refurb
version:             0.2.3.0
synopsis:            Tools for maintaining a database
description:         Tools for maintaining a database
homepage:            https://github.com/ConferOpenSource/refurb#readme
license:             BSD3
category:            Database
maintainer:          oss@vitalbio.com
copyright:           2017 Confer Health, Inc., 2020 Vital Biosciences

dependencies:
  - base >= 4.7 && < 5
  - ansi-wl-pprint
  - bytestring
  - classy-prelude
  - composite-base
  - composite-opaleye
  - dlist
  - exceptions
  - fast-logger
  - lens
  - monad-control
  - monad-logger
  - old-locale
  - opaleye
  - optparse-applicative
  - postgresql-simple
  - process
  - product-profunctors
  - transformers-base
  - template-haskell
  - text
  - these
  - these-lens
  - thyme
  - vector-space

ghc-options:
  - -Wall
  - -O2

library:
  source-dirs: src

tests:
  refurb-test:
    source-dirs: test
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -fno-warn-orphans
    dependencies:
      - refurb
      - hspec
